# This is a basic workflow to help you get started with Actions

name: action test

on:
  push:
    tags:
    - 'v*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & release
      shell: pwsh
      run: |
        md -Name ./artifacts -Force
        Compress-Archive -Path ./app -DestinationPath ./artifacts/app.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "[FAQ](https://github.com/cangzhang/champ-r/wiki/FAQ)\n[CHNAGELOG](https://github.com/cangzhang/champ-r/blob/main/CHANGELOG.md)"
        artifacts: "./LICENSE,./artifacts/app.zip"

